// `botu init [path]` — record the dotfiles repo (the config breadcrumb) and write a
// self-contained botuinit.sh bootstrap into it (one-command fresh-machine setup).

import { mkdir, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { buildCommand } from "@stricli/core";
import { CONFIG_FILE, configBreadcrumbPath } from "../config/load.ts";
import type { BotuContext } from "../context.ts";

const BOOTSTRAP = `#!/usr/bin/env sh
# botuinit.sh — bootstrap this dotfiles repo on a fresh machine. One command:
#   git clone <repo> && ./<repo>/botuinit.sh
# Installs botu if missing, points it here, and applies. Generated by \`botu init\`.
set -eu
REPO="$(cd "$(dirname "$0")" && pwd)"
if ! command -v botu >/dev/null 2>&1; then
  echo "botuinit: installing botu…"
  curl -fsSL https://raw.githubusercontent.com/alxjrvs/botu/main/install.sh | sh
fi
botu init "$REPO"
botu apply "$@"
`;

export const initCommand = buildCommand<Record<never, never>, [string?], BotuContext>({
  docs: { brief: "Record your dotfiles repo and write botuinit.sh" },
  parameters: {
    positional: {
      kind: "tuple",
      parameters: [
        {
          parse: (s: string) => s,
          optional: true,
          placeholder: "path",
          brief: "dotfiles repo (default: cwd)",
        },
      ],
    },
  },
  async func(_flags, path) {
    const target = resolve(path ?? this.cwd);
    try {
      await stat(join(target, CONFIG_FILE));
    } catch {
      return new Error(
        `no ${CONFIG_FILE} at ${target} — point me at your dotfiles repo: botu init /path/to/repo`,
      );
    }
    const crumb = configBreadcrumbPath(this.env);
    await mkdir(dirname(crumb), { recursive: true });
    await writeFile(crumb, `${target}\n`);
    this.process.stdout.write(`botu: dotfiles repo recorded → ${target}\n`);

    const boot = join(target, "botuinit.sh");
    await writeFile(boot, BOOTSTRAP, { mode: 0o755 });
    this.process.stdout.write(`botu: wrote bootstrap → ${boot}\n`);
  },
});
