// `botu init [path]` — record the dotfiles repo (the config breadcrumb, via `botu
// link`) and write a self-contained botuinit.sh bootstrap into it (one-command
// fresh-machine setup).

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildCommand } from "@stricli/core";
import { linkConfigRepo } from "../config/load.ts";
import type { BotuContext } from "../context.ts";

const BOOTSTRAP = `#!/usr/bin/env sh
# botuinit.sh — bootstrap this dotfiles repo on a fresh machine. One command:
#   git clone <repo> && ./<repo>/botuinit.sh
# Installs botu if missing, points it here, and applies. Generated by \`botu init\`.
set -eu
REPO="$(cd "$(dirname "$0")" && pwd)"
if ! command -v botu > /dev/null 2>&1; then
  echo "botuinit: installing botu…"
  curl -fsSL https://raw.githubusercontent.com/alxjrvs/botu/main/install.sh | sh
fi
botu init "$REPO"
botu apply "$@"
`;

export const initCommand = buildCommand<Record<never, never>, [string?], BotuContext>({
  docs: { brief: "Record your dotfiles repo and write botuinit.sh" },
  parameters: {
    positional: {
      kind: "tuple",
      parameters: [
        {
          parse: (s: string) => s,
          optional: true,
          placeholder: "path",
          brief: "dotfiles repo (default: cwd)",
        },
      ],
    },
  },
  async func(_flags, path) {
    // The CWD-linking half is `botu link`; init layers the bootstrap on top.
    let target: string;
    try {
      target = await linkConfigRepo(this.env, path ?? this.cwd);
    } catch (e) {
      return e as Error;
    }
    this.process.stdout.write(`botu: dotfiles repo recorded → ${target}\n`);

    const boot = join(target, "botuinit.sh");
    await writeFile(boot, BOOTSTRAP, { mode: 0o755 });
    this.process.stdout.write(`botu: wrote bootstrap → ${boot}\n`);
  },
});
