// `botu migrate <repo>` — convert a bash botufile to botufile.toml. The LLM-driven
// migration prompt (docs) handles what this mechanical pass can't; warnings flag those.

import { readFile, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildCommand } from "@stricli/core";
import { stringify as stringifyToml } from "smol-toml";
import { parseBashBotufile } from "../config/migrate.ts";
import type { BotuContext } from "../context.ts";

export const migrateCommand = buildCommand<{ force?: boolean }, [string], BotuContext>({
  docs: { brief: "Convert a bash botufile to botufile.toml" },
  parameters: {
    flags: { force: { kind: "boolean", optional: true, brief: "Overwrite an existing botufile.toml" } },
    positional: {
      kind: "tuple",
      parameters: [
        { parse: (s: string) => s, placeholder: "repo", brief: "dotfiles repo with a bash botufile" },
      ],
    },
  },
  async func(flags, repo) {
    let text: string;
    try {
      text = await readFile(join(repo, "botufile"), "utf8");
    } catch {
      return new Error(`no bash botufile at ${repo}`);
    }
    const out = join(repo, "botufile.toml");
    if (!flags.force) {
      try {
        await stat(out);
        return new Error(`${out} already exists — pass --force to overwrite`);
      } catch {
        // absent — safe to write
      }
    }
    const { config, warnings } = parseBashBotufile(text);
    const header = "# Generated by `botu migrate` from the bash botufile. Review before use.\n\n";
    await writeFile(out, header + stringifyToml(config as unknown as Parameters<typeof stringifyToml>[0]));
    for (const w of warnings) this.process.stderr.write(`  ! ${w}\n`);
    this.process.stdout.write(
      `botu: wrote ${out} (${config.section.length} section(s), ${warnings.length} warning(s))\n`,
    );
    return;
  },
});
