// Answering `sudo` from the vault instead of the terminal.
//
// Context, because it decides what this file is *for*. A spawned tool can shell out to `sudo` on
// its own (Homebrew does, for any cask with a `launchctl`/`pkgutil` stanza — `brew upgrade --cask
// <app>`). That used to read as a hang: sudo writes its prompt to /dev/tty, and the active-work
// spinner redraws that same line 11×/second with `\r\x1b[K`, so the prompt was printed and then
// erased — `boom source --update` sat ten minutes on `sudo -u root -E -- /bin/launchctl list
// app.<cask>.app-LaunchAtLoginHelper`. That defect is fixed where it belongs, in the reporter: a
// step that can escalate gives up the line (`spin(…, { mayPrompt })`), so sudo asks and the user
// answers. Being asked directly is the DEFAULT and needs no configuration.
//
// So this file is not the fix for the erased prompt. It's for the case where there is nobody to
// ask: an unattended run (a launchd timer, CI, a remote session) has no one at the terminal, and
// there a visible prompt is still an indefinite block. Configure `[boom].sudo_askpass` and the
// password comes from the vault instead — which also means nothing will prompt, so the animated
// spinner is safe again (see packages.ts, which keys the presentation off SUDO_ASKPASS).
//
// Why an executable shim and not something simpler:
//   • boom can't answer the prompt itself — it doesn't build that sudo argv, Homebrew does. The
//     only seam boom controls is the child's *environment*.
//   • `SUDO_ASKPASS` is sudo's own hook for exactly this, and Homebrew supports it *by contract*,
//     not by accident: it's a documented Homebrew environment variable ("If set, pass the `-A`
//     option when calling sudo(8)" — Library/Homebrew/env_config.rb), implemented in
//     system_command.rb and honored down to skipping the interactive "sudo is required" notice
//     (cask/caskroom.rb). So one env var covers every sudo call brew makes, however deep, however
//     late — which a pre-warmed `sudo -v` timestamp would not, since its 5-minute ticket can
//     expire mid-run and put us right back in the hang.
//   • sudo takes a *path to an executable*, not a command line, so the ref can't be an argument
//     to it — hence a generated file that execs `boom askpass <ref>`.
//
// What lands on disk is the *reference*, never the plaintext: the resolved password exists only
// in the pipe between `boom askpass` and sudo. Writing it to a file would defeat the whole point
// (and contradict resources/secret.ts, which refuses to journal a plaintext for the same reason).
import { join } from "node:path";
import { chmod, mkdir } from "../../lib/fs.ts";
import type { Env } from "../../lib/proc.ts";
import { boomStateDir } from "../state.ts";

// 0700: only the owner may run it. The shim is not itself a secret (it names a vault reference),
// but it *is* a "print me the admin password" button, so it gets no wider audience than the user
// who could have run `op read` by hand anyway.
const SHIM_MODE = 0o700;

export function askpassPath(env: Env): string {
  return join(boomStateDir(env), "askpass");
}

// Single-quote a value for /bin/sh: wrap in '…' and escape any embedded quote as '\''. Paths and
// refs are interpolated into a generated script, and a 1Password item title with a space (or an
// apostrophe) is entirely ordinary — an unquoted ref would word-split and resolve nothing.
function shQuote(s: string): string {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

// The shim's text, separated from the write so it's assertable without touching a filesystem.
// `exec` so sudo's child *is* boom (no orphan shell), and stdout stays the password channel.
export function askpassScript(ref: string, execPath: string, env: Env): string {
  // Pinned rather than inherited, because what sudo forwards to an askpass helper is a function of
  // *sudoers* (`env_reset`, `secure_path`, `env_keep`) — not something boom can know from here. A
  // trimmed PATH means the vault CLI isn't found; a missing HOME means `op` can't locate the
  // session/account config it needs to resolve the reference at all. Measured on this machine the
  // environment did come through intact, so this is belt-and-braces — but it costs two lines and
  // removes a whole class of "works on my box" from the one path that must not fail silently.
  const path = env.PATH ?? "/usr/bin:/bin";
  const home = env.HOME ?? "";
  return `#!/bin/sh
# Generated by boom (engine/secrets/askpass.ts) — do not edit.
# Resolves the boomfile's [boom].sudo_askpass reference and prints it for sudo -A.
PATH=${shQuote(path)}
HOME=${shQuote(home)}
export PATH HOME
exec ${shQuote(execPath)} askpass ${shQuote(ref)}
`;
}

// Materialize the shim under the state dir and hand back its path, for the caller to put in a
// child's SUDO_ASKPASS. Rewritten every run (cheap, and it re-pins PATH/HOME plus the current
// binary path, so a `boom upgrade` or a moved config can't leave a shim pointing at nothing).
export async function installAskpass(ref: string, execPath: string, env: Env): Promise<string> {
  const path = askpassPath(env);
  await mkdir(boomStateDir(env), { recursive: true });
  await Bun.write(path, askpassScript(ref, execPath, env));
  await chmod(path, SHIM_MODE);
  return path;
}
